---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: r2dbc/r2dbc-proxy

inputs:
- name: r2dbc-proxy
- name: r2dbc-spi-artifactory

outputs:
- name: r2dbc-proxy-artifactory

caches:
- path: maven

run:
  path: r2dbc-proxy/ci/build.sh
